name = "backend"
main = "src/index.ts"
compatibility_date = "2025-01-25"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMzJhYWMzMzctY2Q5Mi00Y2Y0LTk2YTUtZTgxMTAwMDQ4ZGMzIiwidGVuYW50X2lkIjoiYjJiNzhmMTBmYTc5MzU3ZDVkYzBmNjI2ZTEzZTljMGUwZmY0MWQzMjViZDc2N2U2MjM0NzllMjVmYTU5YmE2NyIsImludGVybmFsX3NlY3JldCI6IjVmYmMwNDcxLWMyM2ItNDlkNS1hZDliLTQ4YTA1Njk5YmI4NiJ9.g2oGGgzFxmH6nLOuRywvwSNhJB0fruMzNIWm1Pfhj2g"
JWT_SECRET = "Vikas_good_Secret"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1